lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# configuration for `jekyll-readme-index` plugin
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false